# Generated by Django 5.2.12 on 2026-04-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='security_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High Security')], default='normal', max_length=20),
        ),
    ]
