# Generated by Django 5.2.12 on 2026-04-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_expiry_date_document_security_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
